/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as DrawRouteImport } from './routes/draw'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FusionRouteImport } from './routes/fusion'
import { Route as GoddessRouteImport } from './routes/goddess'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PhysicalCollectionRouteImport } from './routes/physical-collection'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as RecruitmentRouteImport } from './routes/recruitment'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as WishPoolsRouteImport } from './routes/wish-pools'
import { Route as ActivitiesIndexRouteImport } from './routes/activities.index'
import { Route as ActivitiesActivityIdRouteImport } from './routes/activities.$activityId'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAlbumTemplatesRouteImport } from './routes/admin.album-templates'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminGoddessesRouteImport } from './routes/admin.goddesses'
import { Route as AnnouncementsIndexRouteImport } from './routes/announcements.index'
import { Route as AnnouncementsAnnouncementIdRouteImport } from './routes/announcements.$announcementId'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAchievementsRouteImport } from './routes/app.achievements'
import { Route as AppGrowthRouteImport } from './routes/app.growth'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppSynthesisRouteImport } from './routes/app.synthesis'
import { Route as AppWalletRouteImport } from './routes/app.wallet'
import { Route as CardsCardIdRouteImport } from './routes/cards.$cardId'
import { Route as CollectorsDemoPlayerRouteImport } from './routes/collectors.demo-player'
import { Route as GoddessIndexRouteImport } from './routes/goddess.index'
import { Route as GoddessDashboardRouteImport } from './routes/goddess.dashboard'
import { Route as GoddessProfileRouteImport } from './routes/goddess.profile'
import { Route as GoddessesIndexRouteImport } from './routes/goddesses.index'
import { Route as GoddessesGoddessIdRouteImport } from './routes/goddesses.$goddessId'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as PoolsIndexRouteImport } from './routes/pools.index'
import { Route as PoolsPoolIdRouteImport } from './routes/pools.$poolId'
import { Route as SeasonsNextRouteImport } from './routes/seasons.next'
import { Route as AdminGoddessesIndexRouteImport } from './routes/admin.goddesses.index'
import { Route as AdminGoddessesIdRouteImport } from './routes/admin.goddesses.$id'
import { Route as AdminPoolsIndexRouteImport } from './routes/admin.pools.index'
import { Route as AdminPoolsPoolIdRouteImport } from './routes/admin.pools.$poolId'
import { Route as AdminPoolsNewRouteImport } from './routes/admin.pools.new'
import { Route as AdminPoolsTemplatesRouteImport } from './routes/admin.pools.templates'
import { Route as AppAlbumIndexRouteImport } from './routes/app.album.index'
import { Route as AppAlbumPoolIdRouteImport } from './routes/app.album.$poolId'
import { Route as AppCardsCardIdRouteImport } from './routes/app.cards.$cardId'
import { Route as AppDrawPoolIdRouteImport } from './routes/app.draw.$poolId'
import { Route as AppPreviewCollectorRouteImport } from './routes/app.preview.collector'
import { Route as AppSettingsIndexRouteImport } from './routes/app.settings.index'
import { Route as AppSettingsPrivacyRouteImport } from './routes/app.settings.privacy'
import { Route as GoddessContractsIndexRouteImport } from './routes/goddess.contracts.index'
import { Route as GoddessContractsIdRouteImport } from './routes/goddess.contracts.$id'
import { Route as GoddessRevenueIndexRouteImport } from './routes/goddess.revenue.index'
import { Route as GoddessRevenueIdRouteImport } from './routes/goddess.revenue.$id'
import { Route as PartnerApplyIndexRouteImport } from './routes/partner.apply.index'
import { Route as PartnerApplyStatusRouteImport } from './routes/partner.apply.status'
import { Route as AdminGoddessesApplicationsIndexRouteImport } from './routes/admin.goddesses.applications.index'
import { Route as AdminGoddessesApplicationsIdRouteImport } from './routes/admin.goddesses.applications.$id'
import { Route as AdminPoolsPoolIdIndexRouteImport } from './routes/admin.pools.$poolId.index'
import { Route as AdminPoolsPoolIdDrawSettingsRouteImport } from './routes/admin.pools.$poolId.draw-settings'
import { Route as AdminPoolsPoolIdSynthesisSettingsRouteImport } from './routes/admin.pools.$poolId.synthesis-settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawRoute = DrawRouteImport.update({
  id: '/draw',
  path: '/draw',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FusionRoute = FusionRouteImport.update({
  id: '/fusion',
  path: '/fusion',
  getParentRoute: () => rootRouteImport,
} as any)
const GoddessRoute = GoddessRouteImport.update({
  id: '/goddess',
  path: '/goddess',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicalCollectionRoute = PhysicalCollectionRouteImport.update({
  id: '/physical-collection',
  path: '/physical-collection',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRoute = RecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const WishPoolsRoute = WishPoolsRouteImport.update({
  id: '/wish-pools',
  path: '/wish-pools',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesIndexRoute = ActivitiesIndexRouteImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesActivityIdRoute = ActivitiesActivityIdRouteImport.update({
  id: '/activities/$activityId',
  path: '/activities/$activityId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlbumTemplatesRoute = AdminAlbumTemplatesRouteImport.update({
  id: '/album-templates',
  path: '/album-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGoddessesRoute = AdminGoddessesRouteImport.update({
  id: '/goddesses',
  path: '/goddesses',
  getParentRoute: () => AdminRoute,
} as any)
const AnnouncementsIndexRoute = AnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsAnnouncementIdRoute =
  AnnouncementsAnnouncementIdRouteImport.update({
    id: '/announcements/$announcementId',
    path: '/announcements/$announcementId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppGrowthRoute = AppGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppSynthesisRoute = AppSynthesisRouteImport.update({
  id: '/synthesis',
  path: '/synthesis',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const CardsCardIdRoute = CardsCardIdRouteImport.update({
  id: '/cards/$cardId',
  path: '/cards/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorsDemoPlayerRoute = CollectorsDemoPlayerRouteImport.update({
  id: '/collectors/demo-player',
  path: '/collectors/demo-player',
  getParentRoute: () => rootRouteImport,
} as any)
const GoddessIndexRoute = GoddessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GoddessRoute,
} as any)
const GoddessDashboardRoute = GoddessDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => GoddessRoute,
} as any)
const GoddessProfileRoute = GoddessProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => GoddessRoute,
} as any)
const GoddessesIndexRoute = GoddessesIndexRouteImport.update({
  id: '/goddesses/',
  path: '/goddesses/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoddessesGoddessIdRoute = GoddessesGoddessIdRouteImport.update({
  id: '/goddesses/$goddessId',
  path: '/goddesses/$goddessId',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerRoute,
} as any)
const PoolsIndexRoute = PoolsIndexRouteImport.update({
  id: '/pools/',
  path: '/pools/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsPoolIdRoute = PoolsPoolIdRouteImport.update({
  id: '/pools/$poolId',
  path: '/pools/$poolId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsNextRoute = SeasonsNextRouteImport.update({
  id: '/seasons/next',
  path: '/seasons/next',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGoddessesIndexRoute = AdminGoddessesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminGoddessesRoute,
} as any)
const AdminGoddessesIdRoute = AdminGoddessesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminGoddessesRoute,
} as any)
const AdminPoolsIndexRoute = AdminPoolsIndexRouteImport.update({
  id: '/pools/',
  path: '/pools/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPoolsPoolIdRoute = AdminPoolsPoolIdRouteImport.update({
  id: '/pools/$poolId',
  path: '/pools/$poolId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPoolsNewRoute = AdminPoolsNewRouteImport.update({
  id: '/pools/new',
  path: '/pools/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPoolsTemplatesRoute = AdminPoolsTemplatesRouteImport.update({
  id: '/pools/templates',
  path: '/pools/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AppAlbumIndexRoute = AppAlbumIndexRouteImport.update({
  id: '/album/',
  path: '/album/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlbumPoolIdRoute = AppAlbumPoolIdRouteImport.update({
  id: '/album/$poolId',
  path: '/album/$poolId',
  getParentRoute: () => AppRoute,
} as any)
const AppCardsCardIdRoute = AppCardsCardIdRouteImport.update({
  id: '/cards/$cardId',
  path: '/cards/$cardId',
  getParentRoute: () => AppRoute,
} as any)
const AppDrawPoolIdRoute = AppDrawPoolIdRouteImport.update({
  id: '/draw/$poolId',
  path: '/draw/$poolId',
  getParentRoute: () => AppRoute,
} as any)
const AppPreviewCollectorRoute = AppPreviewCollectorRouteImport.update({
  id: '/preview/collector',
  path: '/preview/collector',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPrivacyRoute = AppSettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => AppRoute,
} as any)
const GoddessContractsIndexRoute = GoddessContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => GoddessRoute,
} as any)
const GoddessContractsIdRoute = GoddessContractsIdRouteImport.update({
  id: '/contracts/$id',
  path: '/contracts/$id',
  getParentRoute: () => GoddessRoute,
} as any)
const GoddessRevenueIndexRoute = GoddessRevenueIndexRouteImport.update({
  id: '/revenue/',
  path: '/revenue/',
  getParentRoute: () => GoddessRoute,
} as any)
const GoddessRevenueIdRoute = GoddessRevenueIdRouteImport.update({
  id: '/revenue/$id',
  path: '/revenue/$id',
  getParentRoute: () => GoddessRoute,
} as any)
const PartnerApplyIndexRoute = PartnerApplyIndexRouteImport.update({
  id: '/apply/',
  path: '/apply/',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerApplyStatusRoute = PartnerApplyStatusRouteImport.update({
  id: '/apply/status',
  path: '/apply/status',
  getParentRoute: () => PartnerRoute,
} as any)
const AdminGoddessesApplicationsIndexRoute =
  AdminGoddessesApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => AdminGoddessesRoute,
  } as any)
const AdminGoddessesApplicationsIdRoute =
  AdminGoddessesApplicationsIdRouteImport.update({
    id: '/applications/$id',
    path: '/applications/$id',
    getParentRoute: () => AdminGoddessesRoute,
  } as any)
const AdminPoolsPoolIdIndexRoute = AdminPoolsPoolIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPoolsPoolIdRoute,
} as any)
const AdminPoolsPoolIdDrawSettingsRoute =
  AdminPoolsPoolIdDrawSettingsRouteImport.update({
    id: '/draw-settings',
    path: '/draw-settings',
    getParentRoute: () => AdminPoolsPoolIdRoute,
  } as any)
const AdminPoolsPoolIdSynthesisSettingsRoute =
  AdminPoolsPoolIdSynthesisSettingsRouteImport.update({
    id: '/synthesis-settings',
    path: '/synthesis-settings',
    getParentRoute: () => AdminPoolsPoolIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/collection': typeof CollectionRoute
  '/draw': typeof DrawRoute
  '/faq': typeof FaqRoute
  '/fusion': typeof FusionRoute
  '/goddess': typeof GoddessRouteWithChildren
  '/leaderboards': typeof LeaderboardsRoute
  '/partner': typeof PartnerRouteWithChildren
  '/physical-collection': typeof PhysicalCollectionRoute
  '/rankings': typeof RankingsRoute
  '/recruitment': typeof RecruitmentRoute
  '/rules': typeof RulesRoute
  '/wish-pools': typeof WishPoolsRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/admin/album-templates': typeof AdminAlbumTemplatesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/goddesses': typeof AdminGoddessesRouteWithChildren
  '/announcements/$announcementId': typeof AnnouncementsAnnouncementIdRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/growth': typeof AppGrowthRoute
  '/app/history': typeof AppHistoryRoute
  '/app/synthesis': typeof AppSynthesisRoute
  '/app/wallet': typeof AppWalletRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/collectors/demo-player': typeof CollectorsDemoPlayerRoute
  '/goddess/dashboard': typeof GoddessDashboardRoute
  '/goddess/profile': typeof GoddessProfileRoute
  '/goddesses/$goddessId': typeof GoddessesGoddessIdRoute
  '/pools/$poolId': typeof PoolsPoolIdRoute
  '/seasons/next': typeof SeasonsNextRoute
  '/activities/': typeof ActivitiesIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/app/': typeof AppIndexRoute
  '/goddess/': typeof GoddessIndexRoute
  '/goddesses/': typeof GoddessesIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/pools/': typeof PoolsIndexRoute
  '/admin/goddesses/$id': typeof AdminGoddessesIdRoute
  '/admin/pools/$poolId': typeof AdminPoolsPoolIdRouteWithChildren
  '/admin/pools/new': typeof AdminPoolsNewRoute
  '/admin/pools/templates': typeof AdminPoolsTemplatesRoute
  '/app/album/$poolId': typeof AppAlbumPoolIdRoute
  '/app/cards/$cardId': typeof AppCardsCardIdRoute
  '/app/draw/$poolId': typeof AppDrawPoolIdRoute
  '/app/preview/collector': typeof AppPreviewCollectorRoute
  '/app/settings/privacy': typeof AppSettingsPrivacyRoute
  '/goddess/contracts/$id': typeof GoddessContractsIdRoute
  '/goddess/revenue/$id': typeof GoddessRevenueIdRoute
  '/partner/apply/status': typeof PartnerApplyStatusRoute
  '/admin/goddesses/': typeof AdminGoddessesIndexRoute
  '/admin/pools/': typeof AdminPoolsIndexRoute
  '/app/album/': typeof AppAlbumIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/goddess/contracts/': typeof GoddessContractsIndexRoute
  '/goddess/revenue/': typeof GoddessRevenueIndexRoute
  '/partner/apply/': typeof PartnerApplyIndexRoute
  '/admin/goddesses/applications/$id': typeof AdminGoddessesApplicationsIdRoute
  '/admin/pools/$poolId/draw-settings': typeof AdminPoolsPoolIdDrawSettingsRoute
  '/admin/pools/$poolId/synthesis-settings': typeof AdminPoolsPoolIdSynthesisSettingsRoute
  '/admin/goddesses/applications/': typeof AdminGoddessesApplicationsIndexRoute
  '/admin/pools/$poolId/': typeof AdminPoolsPoolIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/draw': typeof DrawRoute
  '/faq': typeof FaqRoute
  '/fusion': typeof FusionRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/physical-collection': typeof PhysicalCollectionRoute
  '/rankings': typeof RankingsRoute
  '/recruitment': typeof RecruitmentRoute
  '/rules': typeof RulesRoute
  '/wish-pools': typeof WishPoolsRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/admin/album-templates': typeof AdminAlbumTemplatesRoute
  '/admin/content': typeof AdminContentRoute
  '/announcements/$announcementId': typeof AnnouncementsAnnouncementIdRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/growth': typeof AppGrowthRoute
  '/app/history': typeof AppHistoryRoute
  '/app/synthesis': typeof AppSynthesisRoute
  '/app/wallet': typeof AppWalletRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/collectors/demo-player': typeof CollectorsDemoPlayerRoute
  '/goddess/dashboard': typeof GoddessDashboardRoute
  '/goddess/profile': typeof GoddessProfileRoute
  '/goddesses/$goddessId': typeof GoddessesGoddessIdRoute
  '/pools/$poolId': typeof PoolsPoolIdRoute
  '/seasons/next': typeof SeasonsNextRoute
  '/activities': typeof ActivitiesIndexRoute
  '/admin': typeof AdminIndexRoute
  '/announcements': typeof AnnouncementsIndexRoute
  '/app': typeof AppIndexRoute
  '/goddess': typeof GoddessIndexRoute
  '/goddesses': typeof GoddessesIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/pools': typeof PoolsIndexRoute
  '/admin/goddesses/$id': typeof AdminGoddessesIdRoute
  '/admin/pools/new': typeof AdminPoolsNewRoute
  '/admin/pools/templates': typeof AdminPoolsTemplatesRoute
  '/app/album/$poolId': typeof AppAlbumPoolIdRoute
  '/app/cards/$cardId': typeof AppCardsCardIdRoute
  '/app/draw/$poolId': typeof AppDrawPoolIdRoute
  '/app/preview/collector': typeof AppPreviewCollectorRoute
  '/app/settings/privacy': typeof AppSettingsPrivacyRoute
  '/goddess/contracts/$id': typeof GoddessContractsIdRoute
  '/goddess/revenue/$id': typeof GoddessRevenueIdRoute
  '/partner/apply/status': typeof PartnerApplyStatusRoute
  '/admin/goddesses': typeof AdminGoddessesIndexRoute
  '/admin/pools': typeof AdminPoolsIndexRoute
  '/app/album': typeof AppAlbumIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/goddess/contracts': typeof GoddessContractsIndexRoute
  '/goddess/revenue': typeof GoddessRevenueIndexRoute
  '/partner/apply': typeof PartnerApplyIndexRoute
  '/admin/goddesses/applications/$id': typeof AdminGoddessesApplicationsIdRoute
  '/admin/pools/$poolId/draw-settings': typeof AdminPoolsPoolIdDrawSettingsRoute
  '/admin/pools/$poolId/synthesis-settings': typeof AdminPoolsPoolIdSynthesisSettingsRoute
  '/admin/goddesses/applications': typeof AdminGoddessesApplicationsIndexRoute
  '/admin/pools/$poolId': typeof AdminPoolsPoolIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/collection': typeof CollectionRoute
  '/draw': typeof DrawRoute
  '/faq': typeof FaqRoute
  '/fusion': typeof FusionRoute
  '/goddess': typeof GoddessRouteWithChildren
  '/leaderboards': typeof LeaderboardsRoute
  '/partner': typeof PartnerRouteWithChildren
  '/physical-collection': typeof PhysicalCollectionRoute
  '/rankings': typeof RankingsRoute
  '/recruitment': typeof RecruitmentRoute
  '/rules': typeof RulesRoute
  '/wish-pools': typeof WishPoolsRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/admin/album-templates': typeof AdminAlbumTemplatesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/goddesses': typeof AdminGoddessesRouteWithChildren
  '/announcements/$announcementId': typeof AnnouncementsAnnouncementIdRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/growth': typeof AppGrowthRoute
  '/app/history': typeof AppHistoryRoute
  '/app/synthesis': typeof AppSynthesisRoute
  '/app/wallet': typeof AppWalletRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/collectors/demo-player': typeof CollectorsDemoPlayerRoute
  '/goddess/dashboard': typeof GoddessDashboardRoute
  '/goddess/profile': typeof GoddessProfileRoute
  '/goddesses/$goddessId': typeof GoddessesGoddessIdRoute
  '/pools/$poolId': typeof PoolsPoolIdRoute
  '/seasons/next': typeof SeasonsNextRoute
  '/activities/': typeof ActivitiesIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/app/': typeof AppIndexRoute
  '/goddess/': typeof GoddessIndexRoute
  '/goddesses/': typeof GoddessesIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/pools/': typeof PoolsIndexRoute
  '/admin/goddesses/$id': typeof AdminGoddessesIdRoute
  '/admin/pools/$poolId': typeof AdminPoolsPoolIdRouteWithChildren
  '/admin/pools/new': typeof AdminPoolsNewRoute
  '/admin/pools/templates': typeof AdminPoolsTemplatesRoute
  '/app/album/$poolId': typeof AppAlbumPoolIdRoute
  '/app/cards/$cardId': typeof AppCardsCardIdRoute
  '/app/draw/$poolId': typeof AppDrawPoolIdRoute
  '/app/preview/collector': typeof AppPreviewCollectorRoute
  '/app/settings/privacy': typeof AppSettingsPrivacyRoute
  '/goddess/contracts/$id': typeof GoddessContractsIdRoute
  '/goddess/revenue/$id': typeof GoddessRevenueIdRoute
  '/partner/apply/status': typeof PartnerApplyStatusRoute
  '/admin/goddesses/': typeof AdminGoddessesIndexRoute
  '/admin/pools/': typeof AdminPoolsIndexRoute
  '/app/album/': typeof AppAlbumIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/goddess/contracts/': typeof GoddessContractsIndexRoute
  '/goddess/revenue/': typeof GoddessRevenueIndexRoute
  '/partner/apply/': typeof PartnerApplyIndexRoute
  '/admin/goddesses/applications/$id': typeof AdminGoddessesApplicationsIdRoute
  '/admin/pools/$poolId/draw-settings': typeof AdminPoolsPoolIdDrawSettingsRoute
  '/admin/pools/$poolId/synthesis-settings': typeof AdminPoolsPoolIdSynthesisSettingsRoute
  '/admin/goddesses/applications/': typeof AdminGoddessesApplicationsIndexRoute
  '/admin/pools/$poolId/': typeof AdminPoolsPoolIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/collection'
    | '/draw'
    | '/faq'
    | '/fusion'
    | '/goddess'
    | '/leaderboards'
    | '/partner'
    | '/physical-collection'
    | '/rankings'
    | '/recruitment'
    | '/rules'
    | '/wish-pools'
    | '/activities/$activityId'
    | '/admin/album-templates'
    | '/admin/content'
    | '/admin/goddesses'
    | '/announcements/$announcementId'
    | '/app/achievements'
    | '/app/growth'
    | '/app/history'
    | '/app/synthesis'
    | '/app/wallet'
    | '/cards/$cardId'
    | '/collectors/demo-player'
    | '/goddess/dashboard'
    | '/goddess/profile'
    | '/goddesses/$goddessId'
    | '/pools/$poolId'
    | '/seasons/next'
    | '/activities/'
    | '/admin/'
    | '/announcements/'
    | '/app/'
    | '/goddess/'
    | '/goddesses/'
    | '/partner/'
    | '/pools/'
    | '/admin/goddesses/$id'
    | '/admin/pools/$poolId'
    | '/admin/pools/new'
    | '/admin/pools/templates'
    | '/app/album/$poolId'
    | '/app/cards/$cardId'
    | '/app/draw/$poolId'
    | '/app/preview/collector'
    | '/app/settings/privacy'
    | '/goddess/contracts/$id'
    | '/goddess/revenue/$id'
    | '/partner/apply/status'
    | '/admin/goddesses/'
    | '/admin/pools/'
    | '/app/album/'
    | '/app/settings/'
    | '/goddess/contracts/'
    | '/goddess/revenue/'
    | '/partner/apply/'
    | '/admin/goddesses/applications/$id'
    | '/admin/pools/$poolId/draw-settings'
    | '/admin/pools/$poolId/synthesis-settings'
    | '/admin/goddesses/applications/'
    | '/admin/pools/$poolId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collection'
    | '/draw'
    | '/faq'
    | '/fusion'
    | '/leaderboards'
    | '/physical-collection'
    | '/rankings'
    | '/recruitment'
    | '/rules'
    | '/wish-pools'
    | '/activities/$activityId'
    | '/admin/album-templates'
    | '/admin/content'
    | '/announcements/$announcementId'
    | '/app/achievements'
    | '/app/growth'
    | '/app/history'
    | '/app/synthesis'
    | '/app/wallet'
    | '/cards/$cardId'
    | '/collectors/demo-player'
    | '/goddess/dashboard'
    | '/goddess/profile'
    | '/goddesses/$goddessId'
    | '/pools/$poolId'
    | '/seasons/next'
    | '/activities'
    | '/admin'
    | '/announcements'
    | '/app'
    | '/goddess'
    | '/goddesses'
    | '/partner'
    | '/pools'
    | '/admin/goddesses/$id'
    | '/admin/pools/new'
    | '/admin/pools/templates'
    | '/app/album/$poolId'
    | '/app/cards/$cardId'
    | '/app/draw/$poolId'
    | '/app/preview/collector'
    | '/app/settings/privacy'
    | '/goddess/contracts/$id'
    | '/goddess/revenue/$id'
    | '/partner/apply/status'
    | '/admin/goddesses'
    | '/admin/pools'
    | '/app/album'
    | '/app/settings'
    | '/goddess/contracts'
    | '/goddess/revenue'
    | '/partner/apply'
    | '/admin/goddesses/applications/$id'
    | '/admin/pools/$poolId/draw-settings'
    | '/admin/pools/$poolId/synthesis-settings'
    | '/admin/goddesses/applications'
    | '/admin/pools/$poolId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/collection'
    | '/draw'
    | '/faq'
    | '/fusion'
    | '/goddess'
    | '/leaderboards'
    | '/partner'
    | '/physical-collection'
    | '/rankings'
    | '/recruitment'
    | '/rules'
    | '/wish-pools'
    | '/activities/$activityId'
    | '/admin/album-templates'
    | '/admin/content'
    | '/admin/goddesses'
    | '/announcements/$announcementId'
    | '/app/achievements'
    | '/app/growth'
    | '/app/history'
    | '/app/synthesis'
    | '/app/wallet'
    | '/cards/$cardId'
    | '/collectors/demo-player'
    | '/goddess/dashboard'
    | '/goddess/profile'
    | '/goddesses/$goddessId'
    | '/pools/$poolId'
    | '/seasons/next'
    | '/activities/'
    | '/admin/'
    | '/announcements/'
    | '/app/'
    | '/goddess/'
    | '/goddesses/'
    | '/partner/'
    | '/pools/'
    | '/admin/goddesses/$id'
    | '/admin/pools/$poolId'
    | '/admin/pools/new'
    | '/admin/pools/templates'
    | '/app/album/$poolId'
    | '/app/cards/$cardId'
    | '/app/draw/$poolId'
    | '/app/preview/collector'
    | '/app/settings/privacy'
    | '/goddess/contracts/$id'
    | '/goddess/revenue/$id'
    | '/partner/apply/status'
    | '/admin/goddesses/'
    | '/admin/pools/'
    | '/app/album/'
    | '/app/settings/'
    | '/goddess/contracts/'
    | '/goddess/revenue/'
    | '/partner/apply/'
    | '/admin/goddesses/applications/$id'
    | '/admin/pools/$poolId/draw-settings'
    | '/admin/pools/$poolId/synthesis-settings'
    | '/admin/goddesses/applications/'
    | '/admin/pools/$poolId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CollectionRoute: typeof CollectionRoute
  DrawRoute: typeof DrawRoute
  FaqRoute: typeof FaqRoute
  FusionRoute: typeof FusionRoute
  GoddessRoute: typeof GoddessRouteWithChildren
  LeaderboardsRoute: typeof LeaderboardsRoute
  PartnerRoute: typeof PartnerRouteWithChildren
  PhysicalCollectionRoute: typeof PhysicalCollectionRoute
  RankingsRoute: typeof RankingsRoute
  RecruitmentRoute: typeof RecruitmentRoute
  RulesRoute: typeof RulesRoute
  WishPoolsRoute: typeof WishPoolsRoute
  ActivitiesActivityIdRoute: typeof ActivitiesActivityIdRoute
  AnnouncementsAnnouncementIdRoute: typeof AnnouncementsAnnouncementIdRoute
  CardsCardIdRoute: typeof CardsCardIdRoute
  CollectorsDemoPlayerRoute: typeof CollectorsDemoPlayerRoute
  GoddessesGoddessIdRoute: typeof GoddessesGoddessIdRoute
  PoolsPoolIdRoute: typeof PoolsPoolIdRoute
  SeasonsNextRoute: typeof SeasonsNextRoute
  ActivitiesIndexRoute: typeof ActivitiesIndexRoute
  AnnouncementsIndexRoute: typeof AnnouncementsIndexRoute
  GoddessesIndexRoute: typeof GoddessesIndexRoute
  PoolsIndexRoute: typeof PoolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw': {
      id: '/draw'
      path: '/draw'
      fullPath: '/draw'
      preLoaderRoute: typeof DrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fusion': {
      id: '/fusion'
      path: '/fusion'
      fullPath: '/fusion'
      preLoaderRoute: typeof FusionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goddess': {
      id: '/goddess'
      path: '/goddess'
      fullPath: '/goddess'
      preLoaderRoute: typeof GoddessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physical-collection': {
      id: '/physical-collection'
      path: '/physical-collection'
      fullPath: '/physical-collection'
      preLoaderRoute: typeof PhysicalCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment': {
      id: '/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof RecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wish-pools': {
      id: '/wish-pools'
      path: '/wish-pools'
      fullPath: '/wish-pools'
      preLoaderRoute: typeof WishPoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/': {
      id: '/activities/'
      path: '/activities'
      fullPath: '/activities/'
      preLoaderRoute: typeof ActivitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/$activityId': {
      id: '/activities/$activityId'
      path: '/activities/$activityId'
      fullPath: '/activities/$activityId'
      preLoaderRoute: typeof ActivitiesActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/album-templates': {
      id: '/admin/album-templates'
      path: '/album-templates'
      fullPath: '/admin/album-templates'
      preLoaderRoute: typeof AdminAlbumTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/goddesses': {
      id: '/admin/goddesses'
      path: '/goddesses'
      fullPath: '/admin/goddesses'
      preLoaderRoute: typeof AdminGoddessesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/announcements/': {
      id: '/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AnnouncementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/$announcementId': {
      id: '/announcements/$announcementId'
      path: '/announcements/$announcementId'
      fullPath: '/announcements/$announcementId'
      preLoaderRoute: typeof AnnouncementsAnnouncementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/growth': {
      id: '/app/growth'
      path: '/growth'
      fullPath: '/app/growth'
      preLoaderRoute: typeof AppGrowthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/synthesis': {
      id: '/app/synthesis'
      path: '/synthesis'
      fullPath: '/app/synthesis'
      preLoaderRoute: typeof AppSynthesisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/cards/$cardId': {
      id: '/cards/$cardId'
      path: '/cards/$cardId'
      fullPath: '/cards/$cardId'
      preLoaderRoute: typeof CardsCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collectors/demo-player': {
      id: '/collectors/demo-player'
      path: '/collectors/demo-player'
      fullPath: '/collectors/demo-player'
      preLoaderRoute: typeof CollectorsDemoPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goddess/': {
      id: '/goddess/'
      path: '/'
      fullPath: '/goddess/'
      preLoaderRoute: typeof GoddessIndexRouteImport
      parentRoute: typeof GoddessRoute
    }
    '/goddess/dashboard': {
      id: '/goddess/dashboard'
      path: '/dashboard'
      fullPath: '/goddess/dashboard'
      preLoaderRoute: typeof GoddessDashboardRouteImport
      parentRoute: typeof GoddessRoute
    }
    '/goddess/profile': {
      id: '/goddess/profile'
      path: '/profile'
      fullPath: '/goddess/profile'
      preLoaderRoute: typeof GoddessProfileRouteImport
      parentRoute: typeof GoddessRoute
    }
    '/goddesses/': {
      id: '/goddesses/'
      path: '/goddesses'
      fullPath: '/goddesses/'
      preLoaderRoute: typeof GoddessesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goddesses/$goddessId': {
      id: '/goddesses/$goddessId'
      path: '/goddesses/$goddessId'
      fullPath: '/goddesses/$goddessId'
      preLoaderRoute: typeof GoddessesGoddessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/pools/': {
      id: '/pools/'
      path: '/pools'
      fullPath: '/pools/'
      preLoaderRoute: typeof PoolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools/$poolId': {
      id: '/pools/$poolId'
      path: '/pools/$poolId'
      fullPath: '/pools/$poolId'
      preLoaderRoute: typeof PoolsPoolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons/next': {
      id: '/seasons/next'
      path: '/seasons/next'
      fullPath: '/seasons/next'
      preLoaderRoute: typeof SeasonsNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/goddesses/': {
      id: '/admin/goddesses/'
      path: '/'
      fullPath: '/admin/goddesses/'
      preLoaderRoute: typeof AdminGoddessesIndexRouteImport
      parentRoute: typeof AdminGoddessesRoute
    }
    '/admin/goddesses/$id': {
      id: '/admin/goddesses/$id'
      path: '/$id'
      fullPath: '/admin/goddesses/$id'
      preLoaderRoute: typeof AdminGoddessesIdRouteImport
      parentRoute: typeof AdminGoddessesRoute
    }
    '/admin/pools/': {
      id: '/admin/pools/'
      path: '/pools'
      fullPath: '/admin/pools/'
      preLoaderRoute: typeof AdminPoolsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pools/$poolId': {
      id: '/admin/pools/$poolId'
      path: '/pools/$poolId'
      fullPath: '/admin/pools/$poolId'
      preLoaderRoute: typeof AdminPoolsPoolIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pools/new': {
      id: '/admin/pools/new'
      path: '/pools/new'
      fullPath: '/admin/pools/new'
      preLoaderRoute: typeof AdminPoolsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pools/templates': {
      id: '/admin/pools/templates'
      path: '/pools/templates'
      fullPath: '/admin/pools/templates'
      preLoaderRoute: typeof AdminPoolsTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/album/': {
      id: '/app/album/'
      path: '/album'
      fullPath: '/app/album/'
      preLoaderRoute: typeof AppAlbumIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/album/$poolId': {
      id: '/app/album/$poolId'
      path: '/album/$poolId'
      fullPath: '/app/album/$poolId'
      preLoaderRoute: typeof AppAlbumPoolIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cards/$cardId': {
      id: '/app/cards/$cardId'
      path: '/cards/$cardId'
      fullPath: '/app/cards/$cardId'
      preLoaderRoute: typeof AppCardsCardIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/draw/$poolId': {
      id: '/app/draw/$poolId'
      path: '/draw/$poolId'
      fullPath: '/app/draw/$poolId'
      preLoaderRoute: typeof AppDrawPoolIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/preview/collector': {
      id: '/app/preview/collector'
      path: '/preview/collector'
      fullPath: '/app/preview/collector'
      preLoaderRoute: typeof AppPreviewCollectorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/privacy': {
      id: '/app/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/app/settings/privacy'
      preLoaderRoute: typeof AppSettingsPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/goddess/contracts/': {
      id: '/goddess/contracts/'
      path: '/contracts'
      fullPath: '/goddess/contracts/'
      preLoaderRoute: typeof GoddessContractsIndexRouteImport
      parentRoute: typeof GoddessRoute
    }
    '/goddess/contracts/$id': {
      id: '/goddess/contracts/$id'
      path: '/contracts/$id'
      fullPath: '/goddess/contracts/$id'
      preLoaderRoute: typeof GoddessContractsIdRouteImport
      parentRoute: typeof GoddessRoute
    }
    '/goddess/revenue/': {
      id: '/goddess/revenue/'
      path: '/revenue'
      fullPath: '/goddess/revenue/'
      preLoaderRoute: typeof GoddessRevenueIndexRouteImport
      parentRoute: typeof GoddessRoute
    }
    '/goddess/revenue/$id': {
      id: '/goddess/revenue/$id'
      path: '/revenue/$id'
      fullPath: '/goddess/revenue/$id'
      preLoaderRoute: typeof GoddessRevenueIdRouteImport
      parentRoute: typeof GoddessRoute
    }
    '/partner/apply/': {
      id: '/partner/apply/'
      path: '/apply'
      fullPath: '/partner/apply/'
      preLoaderRoute: typeof PartnerApplyIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/apply/status': {
      id: '/partner/apply/status'
      path: '/apply/status'
      fullPath: '/partner/apply/status'
      preLoaderRoute: typeof PartnerApplyStatusRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/admin/goddesses/applications/': {
      id: '/admin/goddesses/applications/'
      path: '/applications'
      fullPath: '/admin/goddesses/applications/'
      preLoaderRoute: typeof AdminGoddessesApplicationsIndexRouteImport
      parentRoute: typeof AdminGoddessesRoute
    }
    '/admin/goddesses/applications/$id': {
      id: '/admin/goddesses/applications/$id'
      path: '/applications/$id'
      fullPath: '/admin/goddesses/applications/$id'
      preLoaderRoute: typeof AdminGoddessesApplicationsIdRouteImport
      parentRoute: typeof AdminGoddessesRoute
    }
    '/admin/pools/$poolId/': {
      id: '/admin/pools/$poolId/'
      path: '/'
      fullPath: '/admin/pools/$poolId/'
      preLoaderRoute: typeof AdminPoolsPoolIdIndexRouteImport
      parentRoute: typeof AdminPoolsPoolIdRoute
    }
    '/admin/pools/$poolId/draw-settings': {
      id: '/admin/pools/$poolId/draw-settings'
      path: '/draw-settings'
      fullPath: '/admin/pools/$poolId/draw-settings'
      preLoaderRoute: typeof AdminPoolsPoolIdDrawSettingsRouteImport
      parentRoute: typeof AdminPoolsPoolIdRoute
    }
    '/admin/pools/$poolId/synthesis-settings': {
      id: '/admin/pools/$poolId/synthesis-settings'
      path: '/synthesis-settings'
      fullPath: '/admin/pools/$poolId/synthesis-settings'
      preLoaderRoute: typeof AdminPoolsPoolIdSynthesisSettingsRouteImport
      parentRoute: typeof AdminPoolsPoolIdRoute
    }
  }
}

interface AdminGoddessesRouteChildren {
  AdminGoddessesIdRoute: typeof AdminGoddessesIdRoute
  AdminGoddessesIndexRoute: typeof AdminGoddessesIndexRoute
  AdminGoddessesApplicationsIdRoute: typeof AdminGoddessesApplicationsIdRoute
  AdminGoddessesApplicationsIndexRoute: typeof AdminGoddessesApplicationsIndexRoute
}

const AdminGoddessesRouteChildren: AdminGoddessesRouteChildren = {
  AdminGoddessesIdRoute: AdminGoddessesIdRoute,
  AdminGoddessesIndexRoute: AdminGoddessesIndexRoute,
  AdminGoddessesApplicationsIdRoute: AdminGoddessesApplicationsIdRoute,
  AdminGoddessesApplicationsIndexRoute: AdminGoddessesApplicationsIndexRoute,
}

const AdminGoddessesRouteWithChildren = AdminGoddessesRoute._addFileChildren(
  AdminGoddessesRouteChildren,
)

interface AdminPoolsPoolIdRouteChildren {
  AdminPoolsPoolIdDrawSettingsRoute: typeof AdminPoolsPoolIdDrawSettingsRoute
  AdminPoolsPoolIdSynthesisSettingsRoute: typeof AdminPoolsPoolIdSynthesisSettingsRoute
  AdminPoolsPoolIdIndexRoute: typeof AdminPoolsPoolIdIndexRoute
}

const AdminPoolsPoolIdRouteChildren: AdminPoolsPoolIdRouteChildren = {
  AdminPoolsPoolIdDrawSettingsRoute: AdminPoolsPoolIdDrawSettingsRoute,
  AdminPoolsPoolIdSynthesisSettingsRoute:
    AdminPoolsPoolIdSynthesisSettingsRoute,
  AdminPoolsPoolIdIndexRoute: AdminPoolsPoolIdIndexRoute,
}

const AdminPoolsPoolIdRouteWithChildren =
  AdminPoolsPoolIdRoute._addFileChildren(AdminPoolsPoolIdRouteChildren)

interface AdminRouteChildren {
  AdminAlbumTemplatesRoute: typeof AdminAlbumTemplatesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminGoddessesRoute: typeof AdminGoddessesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPoolsPoolIdRoute: typeof AdminPoolsPoolIdRouteWithChildren
  AdminPoolsNewRoute: typeof AdminPoolsNewRoute
  AdminPoolsTemplatesRoute: typeof AdminPoolsTemplatesRoute
  AdminPoolsIndexRoute: typeof AdminPoolsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlbumTemplatesRoute: AdminAlbumTemplatesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminGoddessesRoute: AdminGoddessesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminPoolsPoolIdRoute: AdminPoolsPoolIdRouteWithChildren,
  AdminPoolsNewRoute: AdminPoolsNewRoute,
  AdminPoolsTemplatesRoute: AdminPoolsTemplatesRoute,
  AdminPoolsIndexRoute: AdminPoolsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppGrowthRoute: typeof AppGrowthRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppSynthesisRoute: typeof AppSynthesisRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAlbumPoolIdRoute: typeof AppAlbumPoolIdRoute
  AppCardsCardIdRoute: typeof AppCardsCardIdRoute
  AppDrawPoolIdRoute: typeof AppDrawPoolIdRoute
  AppPreviewCollectorRoute: typeof AppPreviewCollectorRoute
  AppSettingsPrivacyRoute: typeof AppSettingsPrivacyRoute
  AppAlbumIndexRoute: typeof AppAlbumIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppGrowthRoute: AppGrowthRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppSynthesisRoute: AppSynthesisRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
  AppAlbumPoolIdRoute: AppAlbumPoolIdRoute,
  AppCardsCardIdRoute: AppCardsCardIdRoute,
  AppDrawPoolIdRoute: AppDrawPoolIdRoute,
  AppPreviewCollectorRoute: AppPreviewCollectorRoute,
  AppSettingsPrivacyRoute: AppSettingsPrivacyRoute,
  AppAlbumIndexRoute: AppAlbumIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface GoddessRouteChildren {
  GoddessDashboardRoute: typeof GoddessDashboardRoute
  GoddessProfileRoute: typeof GoddessProfileRoute
  GoddessIndexRoute: typeof GoddessIndexRoute
  GoddessContractsIdRoute: typeof GoddessContractsIdRoute
  GoddessRevenueIdRoute: typeof GoddessRevenueIdRoute
  GoddessContractsIndexRoute: typeof GoddessContractsIndexRoute
  GoddessRevenueIndexRoute: typeof GoddessRevenueIndexRoute
}

const GoddessRouteChildren: GoddessRouteChildren = {
  GoddessDashboardRoute: GoddessDashboardRoute,
  GoddessProfileRoute: GoddessProfileRoute,
  GoddessIndexRoute: GoddessIndexRoute,
  GoddessContractsIdRoute: GoddessContractsIdRoute,
  GoddessRevenueIdRoute: GoddessRevenueIdRoute,
  GoddessContractsIndexRoute: GoddessContractsIndexRoute,
  GoddessRevenueIndexRoute: GoddessRevenueIndexRoute,
}

const GoddessRouteWithChildren =
  GoddessRoute._addFileChildren(GoddessRouteChildren)

interface PartnerRouteChildren {
  PartnerIndexRoute: typeof PartnerIndexRoute
  PartnerApplyStatusRoute: typeof PartnerApplyStatusRoute
  PartnerApplyIndexRoute: typeof PartnerApplyIndexRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerIndexRoute: PartnerIndexRoute,
  PartnerApplyStatusRoute: PartnerApplyStatusRoute,
  PartnerApplyIndexRoute: PartnerApplyIndexRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CollectionRoute: CollectionRoute,
  DrawRoute: DrawRoute,
  FaqRoute: FaqRoute,
  FusionRoute: FusionRoute,
  GoddessRoute: GoddessRouteWithChildren,
  LeaderboardsRoute: LeaderboardsRoute,
  PartnerRoute: PartnerRouteWithChildren,
  PhysicalCollectionRoute: PhysicalCollectionRoute,
  RankingsRoute: RankingsRoute,
  RecruitmentRoute: RecruitmentRoute,
  RulesRoute: RulesRoute,
  WishPoolsRoute: WishPoolsRoute,
  ActivitiesActivityIdRoute: ActivitiesActivityIdRoute,
  AnnouncementsAnnouncementIdRoute: AnnouncementsAnnouncementIdRoute,
  CardsCardIdRoute: CardsCardIdRoute,
  CollectorsDemoPlayerRoute: CollectorsDemoPlayerRoute,
  GoddessesGoddessIdRoute: GoddessesGoddessIdRoute,
  PoolsPoolIdRoute: PoolsPoolIdRoute,
  SeasonsNextRoute: SeasonsNextRoute,
  ActivitiesIndexRoute: ActivitiesIndexRoute,
  AnnouncementsIndexRoute: AnnouncementsIndexRoute,
  GoddessesIndexRoute: GoddessesIndexRoute,
  PoolsIndexRoute: PoolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
